packages:
  - "apps/*"
  - "packages/*"

catalog:
  '@fontsource/ibm-plex-mono': 5.3.0
  '@hey-api/openapi-ts': 0.99.0
  '@redocly/cli': 2.39.0
  '@vitejs/plugin-react': 6.0.1
  react: 19.2.7
  react-dom: 19.2.7
  typescript: 6.0.3
  vite: 8.1.5

catalogMode: strict
