// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, ServerSentEventsResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetCharacterArchiveIndexData, GetCharacterArchiveIndexErrors, GetCharacterArchiveIndexResponses, GetCharacterCloseUpData, GetCharacterCloseUpErrors, GetCharacterCloseUpResponses, GetCharacterLifeJournalData, GetCharacterLifeJournalErrors, GetCharacterLifeJournalResponses, GetCharacterPaperArchiveData, GetCharacterPaperArchiveErrors, GetCharacterPaperArchiveResponses, GetWorldSnapshotData, GetWorldSnapshotErrors, GetWorldSnapshotResponses, StreamWorldEventsData, StreamWorldEventsErrors, StreamWorldEventsResponse, StreamWorldEventsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get the public world snapshot
 *
 * Scene, character positions, market clock, story hooks, and data state for the persistent public world. See `docs/v5/experience-spec.md` §5 and `docs/v5/system-design.md` §7.
 */
export const getWorldSnapshot = <ThrowOnError extends boolean = false>(options?: Options<GetWorldSnapshotData, ThrowOnError>): RequestResult<GetWorldSnapshotResponses, GetWorldSnapshotErrors, ThrowOnError> => (options?.client ?? client).get<GetWorldSnapshotResponses, GetWorldSnapshotErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/world',
    ...options
});

/**
 * Get a character's public close-up
 *
 * Current observable state, current attention, public claims, and unresolved commitments for one character. See `docs/v5/experience-spec.md` §7. Always resolved at the `public_current` audience scope; it does not vary by entitlement.
 */
export const getCharacterCloseUp = <ThrowOnError extends boolean = false>(options: Options<GetCharacterCloseUpData, ThrowOnError>): RequestResult<GetCharacterCloseUpResponses, GetCharacterCloseUpErrors, ThrowOnError> => (options.client ?? client).get<GetCharacterCloseUpResponses, GetCharacterCloseUpErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/characters/{id}/close-up',
    ...options
});

/**
 * Get one page of a character's canonical life journal
 *
 * Cursor-based canonical chronological chapters. Each entry carries only in-chapter consequence summaries and `/archive*` refs — never the full life curve, ledger, relationship graph, or memory index. See `docs/v5/experience-spec.md` §8 and `docs/v5/system-design.md` §11.3's audience table.
 */
export const getCharacterLifeJournal = <ThrowOnError extends boolean = false>(options: Options<GetCharacterLifeJournalData, ThrowOnError>): RequestResult<GetCharacterLifeJournalResponses, GetCharacterLifeJournalErrors, ThrowOnError> => (options.client ?? client).get<GetCharacterLifeJournalResponses, GetCharacterLifeJournalErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/characters/{id}/life-journal',
    ...options
});

/**
 * Get a character's deep-archive index
 *
 * Deep-archive index and per-section entitlement/as-of/visibility. Section payloads are never inlined here — each section's full content is served by its own dedicated endpoint (only `archive/paper` is built in this phase; see the top-level `info.description` for what is not yet built). See `docs/v5/experience-spec.md` §9.1.
 */
export const getCharacterArchiveIndex = <ThrowOnError extends boolean = false>(options: Options<GetCharacterArchiveIndexData, ThrowOnError>): RequestResult<GetCharacterArchiveIndexResponses, GetCharacterArchiveIndexErrors, ThrowOnError> => (options.client ?? client).get<GetCharacterArchiveIndexResponses, GetCharacterArchiveIndexErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/characters/{id}/archive',
    ...options
});

/**
 * Get a character's public paper-trading archive
 *
 * Paper account summary, orders/positions/lots, realized and unrealized P&L, historical action/fill records, the three-aggregate exact version set, `asOf`, and data revisions — restricted to whatever has already passed the public market-time fence. Same-day ticker-specific action, direction, quantity, confidence, and fill are structurally absent from every `historicalActionFills[]. dailyActionDisclosure` until `MarketSessionFinalityAccepted` is recorded for that trading day; see `docs/v5/market-safety.md` ("盤中與盤後揭露") and `docs/v5/system-design.md` §9 and §11.2–§11.3.
 */
export const getCharacterPaperArchive = <ThrowOnError extends boolean = false>(options: Options<GetCharacterPaperArchiveData, ThrowOnError>): RequestResult<GetCharacterPaperArchiveResponses, GetCharacterPaperArchiveErrors, ThrowOnError> => (options.client ?? client).get<GetCharacterPaperArchiveResponses, GetCharacterPaperArchiveErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/characters/{id}/archive/paper',
    ...options
});

/**
 * Subscribe to the public world event stream (SSE)
 *
 * Server-sent event stream for world ticks, scene changes, publicly
 * visible character events, and projection checkpoints. OpenAPI 3.1
 * cannot fully express a multiplexed SSE stream; this path item
 * documents the message shape and semantics rather than a literal
 * single request/response exchange. The `text/event-stream` schema
 * below describes the JSON payload carried in each frame's `data:`
 * field.
 *
 * Edge mapping: the public path `/events/v2/world` is mapped by the
 * edge gateway to the internal SSE router path `/v2/world/stream`
 * (see `docs/v5/system-design.md` §11.3). That internal path is never
 * part of the public contract: it must not appear in the generated
 * TypeScript client, in any error payload, or in any share URL. It is
 * named here only as an architecture note for engineers reading this
 * file, exactly as `system-design.md` itself documents the mapping.
 *
 * Truth semantics: every frame only signals "resource changed" via
 * `eventKind` and `resourceRef`. Clients must treat the SSE payload
 * as a hint, never as truth — after receiving a frame, re-`GET` the
 * referenced public projection endpoint (for example
 * `GET /api/v2/world` or `GET /api/v2/characters/{id}/close-up`)
 * before rendering anything. Clients must not derive dialogue,
 * position, holdings, or market state from a timer or from the SSE
 * payload itself (`docs/v5/system-design.md` §11.4).
 *
 * Reconnect: send the last received `checkpointCursor` as the
 * `Last-Event-ID` header (or the SSE `id:` field, which carries the
 * same cursor) when reconnecting. The stream resumes by replaying
 * checkpoints from that cursor forward; it does not replay from the
 * beginning of world time.
 *
 */
export const streamWorldEvents = <ThrowOnError extends boolean = false>(options?: Options<StreamWorldEventsData, ThrowOnError, StreamWorldEventsResponse>): Promise<ServerSentEventsResult<StreamWorldEventsResponses>> => (options?.client ?? client).sse.get<StreamWorldEventsResponses, StreamWorldEventsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/v2/world',
    ...options
});
