// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://panshi.app' | (string & {});
};

export type Uuid = string;

export type Version = number;

/**
 * Lowercase hex-encoded SHA-256 digest.
 */
export type Digest = string;

export type TruthClass = 'real_fact' | 'statistical_sample' | 'fictional_setting' | 'symbolic_interpretation' | 'simulated_narrative';

/**
 * Cross-cutting projection freshness/availability state (see `docs/v5/system-design.md` §11.3).
 */
export type DataState = 'READY' | 'STALE' | 'HELD' | 'CORRECTED' | 'WITHDRAWN';

/**
 * Versioned audience contract from `docs/v5/system-design.md` §11.3. `canonical_restricted` is never the applied scope of a successful response body — it means the resource cannot be queried at all.
 */
export type AudienceScope = 'public_current' | 'free_archive' | 'subscriber_archive' | 'canonical_restricted';

/**
 * Public-world time-of-day segment from `docs/v5/experience-spec.md` §5.3.
 */
export type MarketSessionPhase = 'pre_market' | 'in_session' | 'after_session' | 'night' | 'non_trading_day';

/**
 * Neutral, non-market-signaling posture. See `docs/v5/market-safety.md` ("盤中可公開") for why these are deliberately neutral rather than transaction-shaped.
 */
export type CharacterPoseState = 'idle' | 'walking' | 'talking' | 'examining' | 'interrupted' | 'avoiding' | 'silent';

/**
 * Foreground/midground/background activity layer (experience-spec §5.1).
 */
export type SceneLayer = 'foreground' | 'midground' | 'background';

/**
 * Rendering level of detail budget (experience-spec §5.1).
 */
export type DetailTier = 'high_detail' | 'edge_silhouette';

/**
 * The fixed set of deep-archive sections from `docs/v5/system-design.md` §11.3, in index order. Every section has its own dedicated endpoint at `/api/v2/characters/{id}/archive/{key}` (`paper`, `relations`, `chart`, `traits`, `memories`, `life`), and each section item there carries a `truthClass` and non-empty `sourceRefs`.
 */
export type ArchiveSectionKey = 'paper' | 'relations' | 'chart' | 'traits' | 'memories' | 'life';

export type V2ReasonCode = 'UNKNOWN_RESOURCE' | 'VISIBILITY_HELD' | 'WITHDRAWN' | 'RIGHTS_REVOKED' | 'PROJECTION_LAGGING' | 'CANONICAL_RESTRICTED' | 'MALFORMED_CURSOR';

export type PaperPositionStatus = 'open' | 'closed' | 'pending';

/**
 * Canonical paper-intent action set (system-design.md §9.2).
 */
export type PaperActionKind = 'BUY' | 'SELL' | 'HOLD' | 'NO_ACTION';

export type PaperDirection = 'no_action' | 'upside' | 'downside';

export type InvalidationCondition = 'not_yet_occurred' | 'occurred' | 'unknown_at_the_time';

/**
 * Whether `MarketSessionFinalityAccepted` has landed for a trading day.
 */
export type MarketSessionFinalityState = 'pending' | 'accepted';

export type DataRevisionKind = 'fact_correction' | 'accounting_correction' | 'position_adjustment';

export type Problem = {
    type: string;
    title: string;
    status: number;
    reasonCode: V2ReasonCode;
    traceId: string;
};

/**
 * One canonical aggregate/fact ref and the exact revision this projection was computed from. Part of the generic `sourceRevisionSet` required on every projection response; see `PaperVersionSet` for the fully-typed triple-aggregate version set used specifically by `/archive/paper`.
 */
export type SourceRevisionRef = {
    refId: string;
    refKind: string;
    revision: Version;
};

/**
 * The three-aggregate exact version set from `docs/v5/system-design.md` §9.1. `paperOrderRefs`/ `paperOrderVersions` and `paperPositionRefs`/`paperPositionVersions` are parallel arrays of equal length, pairwise ordered by stable aggregate ID byte order, with no duplicates. Any input or projection that only carries `paperAccountVersion` without the order/position arrays is not a valid version set.
 */
export type PaperVersionSet = {
    paperAccountRef: Uuid;
    paperAccountVersion: Version;
    paperOrderRefs: Array<Uuid>;
    paperOrderVersions: Array<Version>;
    paperPositionRefs: Array<Uuid>;
    paperPositionVersions: Array<Version>;
    paperVersionSetDigest: Digest;
};

/**
 * An immutable, server-resolved `UtteranceArtifactV1` reference plus its verbatim canonical bytes. Never paired with a second freeform "summary of what they said" string field (system-design.md §11.1, §11.4). Since 2.2.0 no response references this shape directly: every utterance a response carries is a `ClassifiedCharacterUtterance`. It stays as the named base shape that clients may use for the three artifact fields.
 */
export type CharacterUtterance = {
    utteranceArtifactId: string;
    canonicalTextSha256: Digest;
    canonicalTextUtf8: string;
};

/**
 * A `CharacterUtterance` shown as a visible claim of its own: the same immutable artifact ref and verbatim canonical bytes, plus the claim's own `truthClass` (a character's words are `simulated_narrative`). Added in 2.1.0. Since 2.2.0 every utterance a response carries is classified this way, including one nested inside another classified item (`RelationshipSignalView.utterance`): no utterance inherits the class of the item around it.
 */
export type ClassifiedCharacterUtterance = {
    utteranceArtifactId: string;
    canonicalTextSha256: Digest;
    canonicalTextUtf8: string;
    truthClass: TruthClass;
};

/**
 * A later self-narration that is either a verbatim, artifact-backed quote (when a visible `UtteranceArtifactV1` exists) or an unquoted structured summary (the documented fallback shape from `docs/v5/experience-spec.md` §8.4 — never both, and never a system-authored quote). Either variant carries its own `truthClass` (2.1.0).
 */
export type CharacterNarrationOrSummary = {
    kind: 'utterance';
    utteranceArtifactId: string;
    canonicalTextSha256: Digest;
    canonicalTextUtf8: string;
    truthClass: TruthClass;
} | {
    kind: 'summary';
    summaryText: string;
    truthClass: TruthClass;
};

/**
 * Stable-deep-link tombstone projection returned in place of a full character projection once `CharacterContinuityClassChanged` has moved a character to `WITHDRAWN` (system-design.md §3.1, §7.2.1). Existing public URLs never silently point at a different character or a different story.
 */
export type WithdrawnCharacterProjection = {
    projectionVersion: Version;
    sourceGlobalPosition: Version;
    serverNow: string;
    dataState: 'WITHDRAWN';
    visibilityEpoch: Version;
    truthClasses: Array<TruthClass>;
    sourceRevisionSet: Array<SourceRevisionRef>;
    characterId: Uuid;
    /**
     * Policy-safe, non-diagnostic label. Never includes `canonical_restricted` audit detail.
     */
    tombstoneReasonLabel: string;
};

export type AttentionTarget = {
    targetKind: 'person' | 'object' | 'event' | 'unknown';
    label: string;
    /**
     * The truth class of `label` (2.1.0).
     */
    truthClass: TruthClass;
};

export type UnresolvedCommitment = {
    commitmentId: Uuid;
    /**
     * Unquoted structured summary, never a system-authored quote.
     */
    rationaleSummary: string;
    sealedAt: string;
    stillOpen: boolean;
    /**
     * The truth class of this commitment and its `rationaleSummary` (2.1.0).
     */
    truthClass: TruthClass;
};

export type PaperPositionConsequenceHighlight = {
    kind: 'paper_position';
    positionArchiveRef: Uuid;
    /**
     * Signed percentage scaled by 100 (2 implied decimal places); e.g. -840 represents -8.40%.
     */
    unrealizedPnlPercentFixed2: number;
    /**
     * Always shown next to any paper figure (experience-spec §7.2); during a trading session this is the previous session's close.
     */
    asOf: string;
    /**
     * The truth class of this paper figure (2.1.0).
     */
    truthClass: TruthClass;
};

export type RelationshipConsequenceHighlight = {
    kind: 'relationship';
    dyadArchiveRef: Uuid;
    summary: string;
    /**
     * The truth class of `summary` (2.1.0).
     */
    truthClass: TruthClass;
};

export type OccupationConsequenceHighlight = {
    kind: 'occupation';
    summary: string;
    /**
     * The truth class of `summary` (2.1.0).
     */
    truthClass: TruthClass;
};

export type MemoryConsequenceHighlight = {
    kind: 'memory';
    summary: string;
    /**
     * The truth class of `summary` (2.1.0).
     */
    truthClass: TruthClass;
};

/**
 * At most one consequence fragment, shown only when it is this scene's consequence; never a forced-empty performance figure (experience-spec §7.1–§7.2). Absent from `CharacterCloseUp` when there is nothing to show.
 */
export type RecentConsequenceHighlight = PaperPositionConsequenceHighlight | RelationshipConsequenceHighlight | OccupationConsequenceHighlight | MemoryConsequenceHighlight;

export type WorldMarketClock = {
    /**
     * Asia/Taipei market date (system-design.md §7.1).
     */
    marketDate: string;
    sessionPhase: MarketSessionPhase;
    /**
     * Previous finalized trading date backing any paper figures currently visible in the world; `null` when none exists yet.
     */
    asOfTradingDate: string | null;
    /**
     * Next versioned `DeadlineScheduled` boundary (system-design.md §7.1).
     */
    nextBoundaryAt: string;
};

export type WorldSceneState = {
    sceneId: Uuid;
    /**
     * At most two events with clear audiovisual priority at once (experience-spec §5.2).
     */
    activePriorityEventRefs: Array<Uuid>;
};

export type CharacterWorldPosition = {
    characterId: Uuid;
    /**
     * World-space grid coordinate.
     */
    worldX: number;
    /**
     * World-space grid coordinate.
     */
    worldY: number;
    poseState: CharacterPoseState;
    /**
     * The truth class of `poseState` (2.1.0).
     */
    poseStateTruthClass: TruthClass;
    /**
     * What/who the character is currently attending to, if known.
     */
    focusHint: string | null;
    /**
     * The truth class of `focusHint`; non-null exactly when `focusHint` is non-null (2.1.0).
     */
    focusHintTruthClass: TruthClass | null;
    zOrder: number;
    sceneLayer: SceneLayer;
    detailTier: DetailTier;
    sourceEventRefs: Array<Uuid>;
};

/**
 * Lightweight public pointer into a scene, never a ranked or ticker-labeled recommendation (market-safety.md "今日五幕").
 */
export type WorldStoryHookRef = {
    hookId: Uuid;
    characterId: Uuid;
    sceneRef: Uuid;
    label: string;
    /**
     * The truth class of `label` (2.1.0).
     */
    labelTruthClass: TruthClass;
};

export type WorldSnapshot = {
    projectionVersion: Version;
    sourceGlobalPosition: Version;
    serverNow: string;
    dataState: DataState;
    visibilityEpoch: Version;
    truthClasses: Array<TruthClass>;
    sourceRevisionSet: Array<SourceRevisionRef>;
    marketClock: WorldMarketClock;
    worldTickId: Version;
    scene: WorldSceneState;
    characterPositions: Array<CharacterWorldPosition>;
    /**
     * Mirrors the "今日五幕" 0–5 cap (experience-spec §5.4).
     */
    storyHooks: Array<WorldStoryHookRef>;
};

export type CharacterCloseUp = {
    projectionVersion: Version;
    sourceGlobalPosition: Version;
    serverNow: string;
    dataState: DataState;
    visibilityEpoch: Version;
    truthClasses: Array<TruthClass>;
    sourceRevisionSet: Array<SourceRevisionRef>;
    characterId: Uuid;
    displayName: string;
    /**
     * The truth class of `displayName` (2.1.0).
     */
    displayNameTruthClass: TruthClass;
    ageYears: number;
    /**
     * The truth class of `ageYears` (2.1.0): `statistical_sample` only when the age was drawn from a sealed statistical distribution, otherwise the class of the chassis that set it.
     */
    ageYearsTruthClass: TruthClass;
    occupationLabel: string;
    /**
     * The truth class of `occupationLabel` (2.1.0), on the same rule as `ageYearsTruthClass`.
     */
    occupationLabelTruthClass: TruthClass;
    sceneRef: Uuid;
    poseState: CharacterPoseState;
    /**
     * The truth class of `poseState` (2.1.0).
     */
    poseStateTruthClass: TruthClass;
    /**
     * e.g. "正在偷看他說不在意的價格" (experience-spec §7.1).
     */
    currentVerbPhrase: string;
    /**
     * The truth class of `currentVerbPhrase` (2.1.0).
     */
    currentVerbPhraseTruthClass: TruthClass;
    currentAttention?: AttentionTarget;
    /**
     * The one unresolved-contradiction main sentence (experience-spec §7.1).
     */
    unresolvedTensionSummary: string;
    /**
     * The truth class of `unresolvedTensionSummary` (2.1.0).
     */
    unresolvedTensionSummaryTruthClass: TruthClass;
    publicClaim?: ClassifiedCharacterUtterance;
    selfAcknowledgement?: ClassifiedCharacterUtterance;
    recentConsequenceHighlight?: RecentConsequenceHighlight;
    unresolvedCommitments: Array<UnresolvedCommitment>;
};

export type CharacterCloseUpResponse = CharacterCloseUp | WithdrawnCharacterProjection;

export type PaperConsequenceFragment = {
    positionArchiveRef: Uuid;
    heldDays: number;
    /**
     * Signed currency minor units.
     */
    unrealizedPnlMinorUnits: number;
    /**
     * Signed percentage scaled by 100 (2 implied decimal places).
     */
    unrealizedPnlPercentFixed2: number;
    asOf: string;
    /**
     * The truth class of these paper figures (2.1.0).
     */
    truthClass: TruthClass;
};

export type LifeJournalConsequence = unknown & {
    paperConsequence?: PaperConsequenceFragment;
    nonPaperConsequenceSummary?: string;
    /**
     * The truth class of `nonPaperConsequenceSummary`; present exactly when it is (2.1.0).
     */
    nonPaperConsequenceSummaryTruthClass?: TruthClass;
};

/**
 * Only refs into `/archive*` sections — never the full ledger, relationship graph, or memory index inline (system-design.md §11.3).
 */
export type LifeJournalArchiveRefs = {
    paperPositionRefs: Array<Uuid>;
    relationshipDyadRefs: Array<Uuid>;
    memoryRefs: Array<Uuid>;
};

/**
 * One published canonical day-chapter, ordered per experience-spec §8.1. A withheld chapter is never an entry here: it is listed in `LifeJournalPage.heldEntries` as a `HeldLifeJournalEntry`.
 */
export type LifeJournalEntry = {
    entryId: Uuid;
    chapterDate: string;
    /**
     * Always `PUBLIC` on an entry; `HELD` chapters carry only a label and live in `heldEntries`.
     */
    entryVisibility: 'PUBLIC';
    /**
     * `composed` when the chapter's sealed narrative is available; `evidence_card_only` when it is not — then `narrativeSegments` is empty, `sceneSummary` is a fixed system label, and `evidenceCard` still carries the whole consequence.
     */
    narrativeState: 'composed' | 'evidence_card_only';
    narrativeSegments: Array<NarrativeSegment>;
    evidenceCard: EvidenceCard;
    /**
     * The chapter's readable relationship consequence, from its `RelationshipSignalObserved`; `null` when there is none.
     */
    relationshipConsequence: RelationshipSignalView | null;
    /**
     * Non-null exactly when `relationshipConsequence` is `null`.
     */
    relationshipConsequenceNullReason: string | null;
    /**
     * "今天他怎麼了" — the chapter's sealed observable segment; with `narrativeState: evidence_card_only`, a fixed system label that makes no claim about him.
     */
    sceneSummary: string;
    /**
     * The truth class of `sceneSummary` (2.1.0): the class the chapter's sealed observable segment carries, or, for the fixed `evidence_card_only` label, the class of the story projection it stands in for.
     */
    sceneSummaryTruthClass: TruthClass;
    /**
     * 他當時怎麼說 — original self-statement, never rewritten after the fact; absent if nothing was said.
     */
    contemporaneousClaim?: ClassifiedCharacterUtterance;
    /**
     * 他其實知道什麼 — only material the character had actually encountered by then.
     */
    knownAtTheTimeSummary: string;
    /**
     * The truth class of `knownAtTheTimeSummary` (2.1.0).
     */
    knownAtTheTimeSummaryTruthClass: TruthClass;
    /**
     * 他漏掉了什麼 — only revealed after close or after the relevant data went public.
     */
    missedFactsSummary?: string;
    /**
     * The truth class of `missedFactsSummary`; present exactly when it is (2.1.0).
     */
    missedFactsSummaryTruthClass?: TruthClass;
    /**
     * 他做了什麼 — structured summary of the paper action, wait, ask-for-help, concealment, or withdrawal.
     */
    actionSummary: string;
    /**
     * The truth class of `actionSummary` (2.1.0).
     */
    actionSummaryTruthClass: TruthClass;
    consequence: LifeJournalConsequence;
    currentSelfNarration?: CharacterNarrationOrSummary;
    /**
     * 老毛病又回來了 — present only once the same pattern has recurred at least twice.
     */
    recurringPatternRef?: Uuid;
    /**
     * The truth class of the recurring-pattern claim; present exactly when `recurringPatternRef` is (2.1.0).
     */
    recurringPatternTruthClass?: TruthClass;
    /**
     * 還沒完 — the next unresolved question; never previews the outcome.
     */
    openQuestionSummary: string;
    /**
     * The truth class of `openQuestionSummary` (2.1.0).
     */
    openQuestionSummaryTruthClass: TruthClass;
    archiveRefs: LifeJournalArchiveRefs;
};

export type LifeJournalPage = {
    projectionVersion: Version;
    sourceGlobalPosition: Version;
    serverNow: string;
    dataState: DataState;
    visibilityEpoch: Version;
    truthClasses: Array<TruthClass>;
    sourceRevisionSet: Array<SourceRevisionRef>;
    characterId: Uuid;
    appliedAudienceScope: AudienceScope;
    entries: Array<LifeJournalEntry>;
    /**
     * Settled chapters withheld from this page, each with only an id, a date and a reason label. Merge with `entries` by `chapterDate` to render the canonical order.
     */
    heldEntries: Array<HeldLifeJournalEntry>;
    nextCursor: string | null;
};

export type CharacterLifeJournalResponse = LifeJournalPage | WithdrawnCharacterProjection;

export type ArchiveSectionIndexEntry = {
    sectionKey: ArchiveSectionKey;
    /**
     * The audience scope actually applied for the requesting viewer on this section (system-design.md §11.3 audience table).
     */
    viewerAudienceScope: AudienceScope;
    /**
     * One-line index summary, e.g. "目前 2 個部位，其中 1 個理由已失效。"
     */
    summary: string;
    /**
     * The truth class of `summary` (2.1.0).
     */
    summaryTruthClass: TruthClass;
    asOf: string;
    visibilityEpoch: Version;
    /**
     * Same-origin path for this section's dedicated endpoint. Every `ArchiveSectionKey` has one, so this is non-null for all six sections; `null` stays in the type only so a future section key can be indexed before its page exists without a breaking change.
     */
    sectionPath: string | null;
};

export type CharacterArchiveIndex = {
    projectionVersion: Version;
    sourceGlobalPosition: Version;
    serverNow: string;
    dataState: DataState;
    visibilityEpoch: Version;
    truthClasses: Array<TruthClass>;
    sourceRevisionSet: Array<SourceRevisionRef>;
    characterId: Uuid;
    archiveSchemaRevision: string;
    longTermTensionSummary: string;
    /**
     * The truth class of `longTermTensionSummary` (2.1.0).
     */
    longTermTensionSummaryTruthClass: TruthClass;
    /**
     * 最近留下的三件事 (experience-spec §9.1).
     */
    recentHighlights: Array<string>;
    /**
     * Parallel to `recentHighlights` and of equal length: `recentHighlightTruthClasses[i]` is the truth class of `recentHighlights[i]` (2.1.0). A highlight with no class at its index is not rendered.
     */
    recentHighlightTruthClasses: Array<TruthClass>;
    /**
     * One entry per `ArchiveSectionKey` value.
     */
    sections: [
        ArchiveSectionIndexEntry,
        ArchiveSectionIndexEntry,
        ArchiveSectionIndexEntry,
        ArchiveSectionIndexEntry,
        ArchiveSectionIndexEntry,
        ArchiveSectionIndexEntry
    ];
};

export type CharacterArchiveIndexResponse = CharacterArchiveIndex | WithdrawnCharacterProjection;

/**
 * Public projection of `PaperAccount` authoritative fields only — never order lifecycle, fill state, lots, or position P&L (system-design.md §9.1).
 */
export type PaperAccountPublicSummary = {
    currency: string;
    cashMinorUnits: number;
    reservedCashMinorUnits: number;
    /**
     * Baseline virtual principal (e.g. NT$1,000,000; system-design.md §9.1).
     */
    initialCapitalMinorUnits: number;
    correctionRefs: Array<Uuid>;
    asOf: string;
    /**
     * The truth class of this account's paper figures (2.1.0).
     */
    truthClass: TruthClass;
};

export type PaperLotPublic = {
    /**
     * The truth class of this lot's quantity, sealed price and cost basis (2.2.0): his paper figures, `simulated_narrative`, the same class as the position's own figures. A client that cannot read it does not add this lot into any displayed total.
     */
    truthClass: TruthClass;
    lotId: Uuid;
    /**
     * Quantity scaled by 1,000,000 (integer fixed-point; never float).
     */
    quantityFixed6: number;
    /**
     * Per-unit sealed reference price in currency minor units, further scaled by 1,000,000 for sub-minor-unit precision.
     */
    sealedPriceMinorUnitsFixed6: number;
    /**
     * Total lot cost basis in currency minor units.
     */
    costBasisMinorUnits: number;
    sealedPriceRevisionRef: Digest;
};

export type PaperPositionPublic = {
    positionId: Uuid;
    /**
     * The truth class of this position's own figures and states: status, dates, lots, realized and unrealized P&L, mark as-of and invalidation condition (2.1.0).
     */
    truthClass: TruthClass;
    /**
     * Company name/ticker label only — never a recommendation badge.
     */
    instrumentLabel: string;
    /**
     * The truth class of `instrumentLabel`, set by the instrument's source (2.1.0).
     */
    instrumentLabelTruthClass: TruthClass;
    status: PaperPositionStatus;
    openedAt: string;
    lastChangedAt: string;
    closedAt: string | null;
    lots: Array<PaperLotPublic>;
    realizedPnlMinorUnits: number | null;
    unrealizedPnlMinorUnits: number | null;
    unrealizedPnlPercentFixed2: number | null;
    markAsOf: string;
    invalidationCondition: InvalidationCondition;
    /**
     * Unquoted structured summary sealed at the time, never a quote.
     */
    rationaleSummary: string;
    /**
     * The truth class of `rationaleSummary` (2.1.0).
     */
    rationaleSummaryTruthClass: TruthClass;
    /**
     * 同時原話 — present only if a visible UtteranceArtifactV1 exists.
     */
    concurrentClaim?: ClassifiedCharacterUtterance;
    currentNarration?: CharacterNarrationOrSummary;
    influencedByCharacterRefs: Array<Uuid>;
    /**
     * `influencedByCharacterRefs`, resolved to display names and relationship labels with their evidence. Empty when no sealed event shows anyone shaping this position's decisions — a character's own public claim that someone else was the reason is his claim, shown in `/archive/relations`, never here.
     */
    influencedBy: Array<InfluenceRef>;
    /**
     * Non-null exactly when `influencedBy` is empty.
     */
    influencedByEmptyReason: string | null;
    consequenceSummary: string;
    /**
     * The truth class of `consequenceSummary` (2.1.0).
     */
    consequenceSummaryTruthClass: TruthClass;
};

/**
 * Same-day ticker-specific action, direction, quantity, confidence, and fill. This object is structurally absent from `PaperActionFillRecord` until `MarketSessionFinalityAccepted` is recorded for that trading day — never present with nulled fields (market-safety.md "當期交易時段不得公開" / "盤後才可公開").
 */
export type PaperDailyActionDisclosure = {
    /**
     * The truth class of the disclosed action, direction, quantity, confidence and fill (2.1.0).
     */
    truthClass: TruthClass;
    instrumentLabel: string;
    /**
     * The truth class of `instrumentLabel` (2.1.0).
     */
    instrumentLabelTruthClass: TruthClass;
    action: PaperActionKind;
    direction: PaperDirection;
    /**
     * Quantity scaled by 1,000,000.
     */
    quantityFixed6: number;
    /**
     * Signed percentage scaled by 100 (2 implied decimal places).
     */
    confidencePercentFixed2: number;
    /**
     * `null` when the order expired unfilled (`PaperOrderExpired`).
     */
    fill: {
        /**
         * The truth class of the fill's sealed price (2.2.0): his paper fill, `simulated_narrative`, the same class as the disclosure's other paper figures.
         */
        truthClass: TruthClass;
        sealedPriceMinorUnitsFixed6: number;
        sealedPriceRevisionRef: Digest;
        filledAt: string;
    } | null;
    /**
     * Unquoted structured summary sealed before action, never a quote.
     */
    rationaleSummary: string;
    /**
     * The truth class of `rationaleSummary` (2.1.0).
     */
    rationaleSummaryTruthClass: TruthClass;
    concurrentClaim?: ClassifiedCharacterUtterance;
};

/**
 * `dailyActionDisclosure` is an optional key that is only ever serialized once `marketSessionFinalityState` is `accepted` for this record's `tradingDate`; pre-finality responses omit the key entirely rather than sending it nulled out.
 */
export type PaperActionFillRecord = {
    recordId: Uuid;
    positionRef: Uuid;
    /**
     * Asia/Taipei trading session date.
     */
    tradingDate: string;
    marketSessionFinalityState: MarketSessionFinalityState;
    recordDataState: DataState;
    dailyActionDisclosure?: PaperDailyActionDisclosure;
};

export type DataRevisionNote = {
    revisionId: string;
    appliedAt: string;
    kind: DataRevisionKind;
    affectedRefs: Array<Uuid>;
    summary: string;
    /**
     * The truth class of this revision note, set by the source of the fact it corrects (2.1.0).
     */
    truthClass: TruthClass;
};

export type PaperArchiveProjection = {
    projectionVersion: Version;
    sourceGlobalPosition: Version;
    serverNow: string;
    dataState: DataState;
    visibilityEpoch: Version;
    truthClasses: Array<TruthClass>;
    sourceRevisionSet: Array<SourceRevisionRef>;
    characterId: Uuid;
    appliedAudienceScope: AudienceScope;
    /**
     * Explicit as-of for the whole projection; intraday this is always the previous trading session's close (experience-spec §7.2, §9.4).
     */
    asOf: string;
    paperVersionSet: PaperVersionSet;
    account: PaperAccountPublicSummary;
    positions: Array<PaperPositionPublic>;
    historicalActionFills: Array<PaperActionFillRecord>;
    dataRevisions: Array<DataRevisionNote>;
};

export type CharacterPaperArchiveResponse = PaperArchiveProjection | WithdrawnCharacterProjection;

/**
 * Where one archive or evidence item came from: a canonical event (by event type and 1-based global log position — the coordinate `sourceGlobalPosition` counts in — plus the stream it was appended to), or a named anchor in the frozen character chassis for a value no canonical event carries. `eventType` and `globalPosition` are non-null exactly when `kind` is `canonical_event`.
 */
export type ArchiveSourceRef = {
    kind: 'canonical_event' | 'character_seed';
    eventType: string | null;
    globalPosition: Version | null;
    refId: string;
};

/**
 * Never empty — an item with no source is not rendered.
 */
export type ArchiveSourceRefs = Array<ArchiveSourceRef>;

/**
 * One market session and the journal entry it published, if any.
 */
export type ArchiveSessionPointer = {
    sessionDate: string;
    journalEntryRef: Uuid | null;
};

/**
 * A counterpart resolved to a display name and relationship label. The raw canonical acquaintance key is never shown to a viewer.
 */
export type ArchivePersonLabel = {
    displayName: string;
    relationLabel: string;
    /**
     * The truth class of this person's display name and relationship label (2.2.0). A counterpart is authored chassis, so `fictional_setting`, independent of the class of the memory that mentions them.
     */
    truthClass: TruthClass;
};

/**
 * One segment of the chapter's sealed `StoryChapterComposed`, in sealed order. A claim segment carries the artifact's canonical bytes verbatim; a narrator segment is never first person.
 */
export type NarrativeSegment = {
    segmentId: string;
    kind: 'narrator';
    truthClass: TruthClass;
    text: string;
    sourceRefs: ArchiveSourceRefs;
} | {
    segmentId: string;
    kind: 'character_claim';
    truthClass: TruthClass;
    utteranceArtifactId: Uuid;
    canonicalTextSha256: Digest;
    canonicalTextUtf8: string;
    sourceRefs: ArchiveSourceRefs;
};

/**
 * The committed intent, as a fixed label. It says what, never why.
 */
export type EvidenceAction = {
    kind: PaperActionKind;
    label: string;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

/**
 * The session's paper consequence, from canonical ledger events only: filled quantity and sealed price with the manifest that sealed it (`null` on a day without a fill), the realized P&L the session booked, the unrealized P&L its last mark left (`null` without a mark), and fees and taxes, all integer minor units or `*Fixed6`. Equal to the same trading day's figures in `/archive/paper`.
 */
export type EvidencePaperOutcome = {
    positionRef: Uuid;
    filledQuantityFixed6: number | null;
    sealedPriceMinorUnitsFixed6: number | null;
    fillPriceSourceRef: Digest | null;
    markPriceSourceRef: Digest | null;
    realizedPnlMinorUnits: number;
    unrealizedPnlMinorUnits: number | null;
    feeMinorUnits: number;
    taxMinorUnits: number;
    asOf: string;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

/**
 * A sealed `UtteranceArtifactV1`, verbatim, with its surface.
 */
export type EvidenceQuotedUtterance = {
    utteranceArtifactId: Uuid;
    canonicalTextSha256: Digest;
    canonicalTextUtf8: string;
    surface: 'public_claim' | 'self_acknowledged';
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

export type EvidenceMemoryRef = {
    memoryRef: Uuid;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

export type EvidenceRelationshipRef = {
    dyadRef: Uuid;
    relationshipSignalRef: Uuid;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

/**
 * The typed consequence card of one chapter, built from canonical events only, so it survives the chapter's rich narrative failing (`docs/v5/system-design.md` "Story generation failure"). It carries no first-person sentence: its only prose is a fixed action label and fixed empty-reason labels.
 */
export type EvidenceCard = {
    action: EvidenceAction;
    paperOutcome: EvidencePaperOutcome | null;
    /**
     * Non-null exactly when `paperOutcome` is `null`.
     */
    paperOutcomeNullReason: string | null;
    quotedUtterances: Array<EvidenceQuotedUtterance>;
    memoryRefs: Array<EvidenceMemoryRef>;
    relationshipRefs: Array<EvidenceRelationshipRef>;
};

/**
 * One `RelationshipSignalObserved`, readable: the counterpart by display name and relationship label, the signal kind, the sealed claim that caused it (verbatim from its artifact, same hash), and the memory it left.
 */
export type RelationshipSignalView = {
    dyadRef: Uuid;
    relationshipSignalRef: Uuid;
    displayName: string;
    /**
     * The truth class of `displayName` (2.2.0): the counterpart is authored chassis, `fictional_setting`. `truthClass` below classifies the signal (his act), not who she is.
     */
    displayNameTruthClass: TruthClass;
    relationLabel: string;
    /**
     * The truth class of `relationLabel` (2.2.0), as `displayNameTruthClass`.
     */
    relationLabelTruthClass: TruthClass;
    signalKind: 'public_outcome_attribution';
    summary: string;
    /**
     * The sealed sentence that caused the signal, verbatim, with its own `truthClass` (2.2.0; `CharacterUtterance` before).
     */
    utterance: ClassifiedCharacterUtterance;
    consequenceMemoryRefs: Array<Uuid>;
    observedAt: string;
    sessionDate: string;
    journalEntryRef: Uuid | null;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

/**
 * A settled chapter withheld from the public journal. It carries its identity, its date and one reason label — no content field exists on this shape, so nothing about the day can leak through it.
 */
export type HeldLifeJournalEntry = {
    entryId: Uuid;
    chapterDate: string;
    entryVisibility: 'HELD';
    heldReasonLabel: string;
};

/**
 * A character or acquaintance a sealed event shows shaping this position's decisions, resolved to a display name and relationship label.
 */
export type InfluenceRef = {
    displayName: string;
    relationLabel: string;
    influenceSummary: string;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

/**
 * One-way and observable — what he did around her, never her words.
 */
export type ArchiveObservedInteraction = {
    sessionDate: string;
    journalEntryRef: Uuid | null;
    observableAction: string;
    direction: 'one_way_observed';
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

/**
 * The counterpart's side of the relationship. `unknown` whenever she has no sealed utterance — the archive never writes a line or a reaction for her (experience-spec §9.5: 尚未說出口的部分只能標未知).
 */
export type ArchiveCounterpartAccount = {
    state: 'unknown';
    reasonLabel: string;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

export type ArchiveAcquaintance = {
    dyadRef: Uuid;
    displayName: string;
    relationLabel: string;
    relationNote: string;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
    observedInteractions: Array<ArchiveObservedInteraction>;
    observedInteractionsEmptyReason: string | null;
    relationshipSignals: Array<RelationshipSignalView>;
    relationshipSignalsEmptyReason: string | null;
    counterpartAccount: ArchiveCounterpartAccount;
};

export type RelationsArchiveProjection = {
    projectionVersion: Version;
    sourceGlobalPosition: Version;
    serverNow: string;
    dataState: DataState;
    visibilityEpoch: Version;
    truthClasses: Array<TruthClass>;
    sourceRevisionSet: Array<SourceRevisionRef>;
    characterId: Uuid;
    appliedAudienceScope: AudienceScope;
    sectionKey: 'relations';
    asOf: string;
    acquaintances: Array<ArchiveAcquaintance>;
    acquaintancesEmptyReason: string | null;
};

export type CharacterRelationsArchiveResponse = RelationsArchiveProjection | WithdrawnCharacterProjection;

/**
 * The fictional birth identity. Never a real person's data.
 */
export type ArchiveBirthIdentity = {
    birthDate: string;
    birthRegionLabel: string;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

/**
 * One placement computed from the sealed birth data.
 */
export type ChartPlacement = {
    placementLabel: string;
    signLabel: string;
    truthClass: 'symbolic_interpretation';
    sourceRefs: ArchiveSourceRefs;
};

/**
 * A chapter whose sealed symbolic segment invoked the motif, quoted as sealed.
 */
export type ChartMotifInvocation = {
    sessionDate: string;
    journalEntryRef: Uuid | null;
    readingText: string;
    truthClass: 'symbolic_interpretation';
    sourceRefs: ArchiveSourceRefs;
};

/**
 * A symbolic theme. It reaches behaviour only through attention and interpretation; `effectScopeLabel` says so in words, and no field links it to a price, a direction or paper performance.
 */
export type ChartMotif = {
    motifLabel: string;
    effectScopeLabel: string;
    activeWindow: {
        activeFrom: string;
        activeUntil: string;
    };
    activeSessions: Array<ArchiveSessionPointer>;
    invocations: Array<ChartMotifInvocation>;
    invocationsEmptyReason: string | null;
    truthClass: 'symbolic_interpretation';
    sourceRefs: ArchiveSourceRefs;
};

export type ChartArchiveProjection = {
    projectionVersion: Version;
    sourceGlobalPosition: Version;
    serverNow: string;
    dataState: DataState;
    visibilityEpoch: Version;
    truthClasses: Array<TruthClass>;
    sourceRevisionSet: Array<SourceRevisionRef>;
    characterId: Uuid;
    appliedAudienceScope: AudienceScope;
    sectionKey: 'chart';
    asOf: string;
    birthIdentity: ArchiveBirthIdentity;
    placements: Array<ChartPlacement>;
    placementsEmptyReason: string | null;
    motifs: Array<ChartMotif>;
};

export type CharacterChartArchiveResponse = ChartArchiveProjection | WithdrawnCharacterProjection;

/**
 * One continuous four-axis preference on the canonical `-10000..=10000` basis-point axis; negative leans to the low pole. Not a type label and not a capability score.
 */
export type TraitAxis = {
    axisKey: 'social' | 'information' | 'decision' | 'closure';
    lowPoleLabel: string;
    highPoleLabel: string;
    orientationBp: number;
    leaningLabel: string;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

export type TraitLabel = {
    label: string;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

/**
 * Cultural self-description and social tone only; never a capability or market term.
 */
export type TraitBloodType = {
    bloodType: 'A' | 'B' | 'O' | 'AB';
    effectScopeLabel: string;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

/**
 * How he describes himself, from his sealed self-narrative memory; not a quote.
 */
export type TraitSelfDescription = {
    label: string;
    memoryRef: Uuid;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

export type TraitHabit = {
    label: string;
    evidenceSessions: Array<ArchiveSessionPointer>;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

/**
 * A fallible pattern detected from sealed state and history.
 */
export type BiasKind = 'fomo_chase' | 'confirmation_bias' | 'sunk_cost_escalation' | 'rationalization_switch' | 'blame_shift';

/**
 * One sealed occurrence of a pattern, beside the sessions that evidence it. Listed once per occurrence; no count, total or score is attached.
 */
export type BiasOccurrence = {
    biasKind: BiasKind;
    biasLabel: string;
    sessionDate: string;
    journalEntryRef: Uuid | null;
    evidenceSessions: Array<ArchiveSessionPointer>;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

/**
 * A session where a pattern he had shown did not happen.
 */
export type BiasCounterExample = {
    biasKind: BiasKind;
    sessionDate: string;
    journalEntryRef: Uuid | null;
    observedLabel: string;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

export type TraitsArchiveProjection = {
    projectionVersion: Version;
    sourceGlobalPosition: Version;
    serverNow: string;
    dataState: DataState;
    visibilityEpoch: Version;
    truthClasses: Array<TruthClass>;
    sourceRevisionSet: Array<SourceRevisionRef>;
    characterId: Uuid;
    appliedAudienceScope: AudienceScope;
    sectionKey: 'traits';
    asOf: string;
    fourAxis: [
        TraitAxis,
        TraitAxis,
        TraitAxis,
        TraitAxis
    ];
    coreNeed: TraitLabel;
    coreFear: TraitLabel;
    bloodType: TraitBloodType;
    selfDescription: TraitSelfDescription;
    habits: Array<TraitHabit>;
    biasOccurrences: Array<BiasOccurrence>;
    biasOccurrencesEmptyReason: string | null;
    counterExamples: Array<BiasCounterExample>;
    counterExamplesEmptyReason: string | null;
};

export type CharacterTraitsArchiveResponse = TraitsArchiveProjection | WithdrawnCharacterProjection;

/**
 * A later sealed reading of the same memory, shown beside the original.
 */
export type MemoryReinterpretation = {
    reinterpretedAt: string;
    note: string;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

/**
 * One sealed memory whose visibility allows the archive to show it.
 */
export type ArchiveMemory = {
    memoryRef: Uuid;
    memoryKind: 'episodic' | 'belief' | 'relationship' | 'self_narrative';
    kindLabel: string;
    formedAt: string;
    sessionDate: string | null;
    journalEntryRef: Uuid | null;
    formedBeforeFirstSession: boolean;
    note: string;
    involvedPeople: Array<ArchivePersonLabel>;
    emotionalValence: 'negative' | 'neutral' | 'positive';
    confidenceBp: number;
    /**
     * Never `canonical_restricted`; those memories are not listed at all.
     */
    visibility: 'subscriber_archive' | 'public_edition';
    reinterpretations: Array<MemoryReinterpretation>;
    reinterpretationsEmptyReason: string | null;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

export type MemoriesArchiveProjection = {
    projectionVersion: Version;
    sourceGlobalPosition: Version;
    serverNow: string;
    dataState: DataState;
    visibilityEpoch: Version;
    truthClasses: Array<TruthClass>;
    sourceRevisionSet: Array<SourceRevisionRef>;
    characterId: Uuid;
    appliedAudienceScope: AudienceScope;
    sectionKey: 'memories';
    asOf: string;
    memories: Array<ArchiveMemory>;
    memoriesEmptyReason: string | null;
};

export type CharacterMemoriesArchiveResponse = MemoriesArchiveProjection | WithdrawnCharacterProjection;

/**
 * A fictional adult resident. Nothing here identifies a real person.
 */
export type LifeIdentity = {
    displayName: string;
    ageYears: number;
    occupationLabel: string;
    birthDate: string;
    birthRegionLabel: string;
    adultFictionalResident: true;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

export type LifeMilestone = {
    ageYears: number;
    label: string;
    memoryRef: Uuid | null;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

export type LifeOriginMemory = {
    memoryRef: Uuid;
    note: string;
    formedAt: string;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

/**
 * A life facet the chassis never sealed. Listed, not written.
 */
export type LifeUnrecordedFacet = {
    facetKey: 'family_structure' | 'education' | 'financial_responsibility';
    reasonLabel: string;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

/**
 * One market session in the canonical timeline and its chapter, if published.
 */
export type LifeChapterPointer = {
    sessionDate: string;
    chapterState: 'published' | 'in_session';
    journalEntryRef: Uuid | null;
    truthClass: TruthClass;
    sourceRefs: ArchiveSourceRefs;
};

export type LifeArchiveProjection = {
    projectionVersion: Version;
    sourceGlobalPosition: Version;
    serverNow: string;
    dataState: DataState;
    visibilityEpoch: Version;
    truthClasses: Array<TruthClass>;
    sourceRevisionSet: Array<SourceRevisionRef>;
    characterId: Uuid;
    appliedAudienceScope: AudienceScope;
    sectionKey: 'life';
    asOf: string;
    identity: LifeIdentity;
    milestones: Array<LifeMilestone>;
    originMemories: Array<LifeOriginMemory>;
    unrecordedFacets: Array<LifeUnrecordedFacet>;
    joinedWorldOn: string;
    chapterTimeline: Array<LifeChapterPointer>;
};

export type CharacterLifeArchiveResponse = LifeArchiveProjection | WithdrawnCharacterProjection;

/**
 * The JSON shape carried in each SSE frame's `data:` field for `GET /events/v2/world`. This only signals "resource changed" — never authoritative content; clients must re-`GET` `resourceRef`.
 */
export type WorldStreamEventEnvelope = {
    eventKind: 'world_tick' | 'scene_change' | 'character_event' | 'projection_checkpoint';
    /**
     * Same-origin public path the client should re-`GET`, e.g. `/api/v2/world` or `/api/v2/characters/{id}/close-up`. Never a source of truth by itself.
     */
    resourceRef: string;
    /**
     * Reconnect cursor; resend as `Last-Event-ID` (or the SSE `id:` field carries the same value) to resume from this checkpoint.
     */
    checkpointCursor: string;
    visibilityEpoch: Version;
    serverNow: string;
};

export type CharacterId = Uuid;

export type Cursor = string;

export type Limit = number;

export type LastEventId = string;

export type GetWorldSnapshotData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v2/world';
};

export type GetWorldSnapshotErrors = {
    /**
     * Unknown or inaccessible resource.
     */
    404: Problem;
};

export type GetWorldSnapshotError = GetWorldSnapshotErrors[keyof GetWorldSnapshotErrors];

export type GetWorldSnapshotResponses = {
    /**
     * Current public world snapshot.
     */
    200: WorldSnapshot;
};

export type GetWorldSnapshotResponse = GetWorldSnapshotResponses[keyof GetWorldSnapshotResponses];

export type GetCharacterCloseUpData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/v2/characters/{id}/close-up';
};

export type GetCharacterCloseUpErrors = {
    /**
     * Unknown or inaccessible resource.
     */
    404: Problem;
};

export type GetCharacterCloseUpError = GetCharacterCloseUpErrors[keyof GetCharacterCloseUpErrors];

export type GetCharacterCloseUpResponses = {
    /**
     * Character close-up, or a tombstone projection if the character has been withdrawn.
     */
    200: CharacterCloseUpResponse;
};

export type GetCharacterCloseUpResponse = GetCharacterCloseUpResponses[keyof GetCharacterCloseUpResponses];

export type GetCharacterLifeJournalData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/api/v2/characters/{id}/life-journal';
};

export type GetCharacterLifeJournalErrors = {
    /**
     * Malformed or expired cursor.
     */
    400: Problem;
    /**
     * Unknown or inaccessible resource.
     */
    404: Problem;
};

export type GetCharacterLifeJournalError = GetCharacterLifeJournalErrors[keyof GetCharacterLifeJournalErrors];

export type GetCharacterLifeJournalResponses = {
    /**
     * One page of life-journal entries, or a tombstone projection if the character has been withdrawn.
     */
    200: CharacterLifeJournalResponse;
};

export type GetCharacterLifeJournalResponse = GetCharacterLifeJournalResponses[keyof GetCharacterLifeJournalResponses];

export type GetCharacterArchiveIndexData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/v2/characters/{id}/archive';
};

export type GetCharacterArchiveIndexErrors = {
    /**
     * Unknown or inaccessible resource.
     */
    404: Problem;
};

export type GetCharacterArchiveIndexError = GetCharacterArchiveIndexErrors[keyof GetCharacterArchiveIndexErrors];

export type GetCharacterArchiveIndexResponses = {
    /**
     * Deep-archive index, or a tombstone projection if the character has been withdrawn.
     */
    200: CharacterArchiveIndexResponse;
};

export type GetCharacterArchiveIndexResponse = GetCharacterArchiveIndexResponses[keyof GetCharacterArchiveIndexResponses];

export type GetCharacterPaperArchiveData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/v2/characters/{id}/archive/paper';
};

export type GetCharacterPaperArchiveErrors = {
    /**
     * Unknown or inaccessible resource.
     */
    404: Problem;
};

export type GetCharacterPaperArchiveError = GetCharacterPaperArchiveErrors[keyof GetCharacterPaperArchiveErrors];

export type GetCharacterPaperArchiveResponses = {
    /**
     * Public paper-trading archive projection, or a tombstone projection if the character has been withdrawn.
     */
    200: CharacterPaperArchiveResponse;
};

export type GetCharacterPaperArchiveResponse = GetCharacterPaperArchiveResponses[keyof GetCharacterPaperArchiveResponses];

export type GetCharacterRelationsArchiveData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/v2/characters/{id}/archive/relations';
};

export type GetCharacterRelationsArchiveErrors = {
    /**
     * Unknown or inaccessible resource.
     */
    404: Problem;
};

export type GetCharacterRelationsArchiveError = GetCharacterRelationsArchiveErrors[keyof GetCharacterRelationsArchiveErrors];

export type GetCharacterRelationsArchiveResponses = {
    /**
     * Relations section, or a tombstone projection if the character has been withdrawn.
     */
    200: CharacterRelationsArchiveResponse;
};

export type GetCharacterRelationsArchiveResponse = GetCharacterRelationsArchiveResponses[keyof GetCharacterRelationsArchiveResponses];

export type GetCharacterChartArchiveData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/v2/characters/{id}/archive/chart';
};

export type GetCharacterChartArchiveErrors = {
    /**
     * Unknown or inaccessible resource.
     */
    404: Problem;
};

export type GetCharacterChartArchiveError = GetCharacterChartArchiveErrors[keyof GetCharacterChartArchiveErrors];

export type GetCharacterChartArchiveResponses = {
    /**
     * Chart section, or a tombstone projection if the character has been withdrawn.
     */
    200: CharacterChartArchiveResponse;
};

export type GetCharacterChartArchiveResponse = GetCharacterChartArchiveResponses[keyof GetCharacterChartArchiveResponses];

export type GetCharacterTraitsArchiveData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/v2/characters/{id}/archive/traits';
};

export type GetCharacterTraitsArchiveErrors = {
    /**
     * Unknown or inaccessible resource.
     */
    404: Problem;
};

export type GetCharacterTraitsArchiveError = GetCharacterTraitsArchiveErrors[keyof GetCharacterTraitsArchiveErrors];

export type GetCharacterTraitsArchiveResponses = {
    /**
     * Traits section, or a tombstone projection if the character has been withdrawn.
     */
    200: CharacterTraitsArchiveResponse;
};

export type GetCharacterTraitsArchiveResponse = GetCharacterTraitsArchiveResponses[keyof GetCharacterTraitsArchiveResponses];

export type GetCharacterMemoriesArchiveData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/v2/characters/{id}/archive/memories';
};

export type GetCharacterMemoriesArchiveErrors = {
    /**
     * Unknown or inaccessible resource.
     */
    404: Problem;
};

export type GetCharacterMemoriesArchiveError = GetCharacterMemoriesArchiveErrors[keyof GetCharacterMemoriesArchiveErrors];

export type GetCharacterMemoriesArchiveResponses = {
    /**
     * Memories section, or a tombstone projection if the character has been withdrawn.
     */
    200: CharacterMemoriesArchiveResponse;
};

export type GetCharacterMemoriesArchiveResponse = GetCharacterMemoriesArchiveResponses[keyof GetCharacterMemoriesArchiveResponses];

export type GetCharacterLifeArchiveData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/v2/characters/{id}/archive/life';
};

export type GetCharacterLifeArchiveErrors = {
    /**
     * Unknown or inaccessible resource.
     */
    404: Problem;
};

export type GetCharacterLifeArchiveError = GetCharacterLifeArchiveErrors[keyof GetCharacterLifeArchiveErrors];

export type GetCharacterLifeArchiveResponses = {
    /**
     * Life section, or a tombstone projection if the character has been withdrawn.
     */
    200: CharacterLifeArchiveResponse;
};

export type GetCharacterLifeArchiveResponse = GetCharacterLifeArchiveResponses[keyof GetCharacterLifeArchiveResponses];

export type StreamWorldEventsData = {
    body?: never;
    headers?: {
        'Last-Event-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/events/v2/world';
};

export type StreamWorldEventsErrors = {
    /**
     * Malformed or expired `Last-Event-ID` reconnect cursor.
     */
    400: Problem;
};

export type StreamWorldEventsError = StreamWorldEventsErrors[keyof StreamWorldEventsErrors];

export type StreamWorldEventsResponses = {
    /**
     * Open SSE stream. Each frame's `data:` payload is one `WorldStreamEventEnvelope`.
     */
    200: WorldStreamEventEnvelope;
};

export type StreamWorldEventsResponse = StreamWorldEventsResponses[keyof StreamWorldEventsResponses];
