// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://panshi.app' | (string & {});
};

export type Uuid = string;

export type Version = number;

/**
 * Lowercase hex-encoded SHA-256 digest.
 */
export type Digest = string;

export type TruthClass = 'real_fact' | 'statistical_sample' | 'fictional_setting' | 'symbolic_interpretation' | 'simulated_narrative';

/**
 * Cross-cutting projection freshness/availability state (see `docs/v5/system-design.md` §11.3).
 */
export type DataState = 'READY' | 'STALE' | 'HELD' | 'CORRECTED' | 'WITHDRAWN';

/**
 * Versioned audience contract from `docs/v5/system-design.md` §11.3. `canonical_restricted` is never the applied scope of a successful response body — it means the resource cannot be queried at all.
 */
export type AudienceScope = 'public_current' | 'free_archive' | 'subscriber_archive' | 'canonical_restricted';

/**
 * Public-world time-of-day segment from `docs/v5/experience-spec.md` §5.3.
 */
export type MarketSessionPhase = 'pre_market' | 'in_session' | 'after_session' | 'night' | 'non_trading_day';

/**
 * Neutral, non-market-signaling posture. See `docs/v5/market-safety.md` ("盤中可公開") for why these are deliberately neutral rather than transaction-shaped.
 */
export type CharacterPoseState = 'idle' | 'walking' | 'talking' | 'examining' | 'interrupted' | 'avoiding' | 'silent';

/**
 * Foreground/midground/background activity layer (experience-spec §5.1).
 */
export type SceneLayer = 'foreground' | 'midground' | 'background';

/**
 * Rendering level of detail budget (experience-spec §5.1).
 */
export type DetailTier = 'high_detail' | 'edge_silhouette';

/**
 * The fixed set of deep-archive sections from `docs/v5/system-design.md` §11.3. Only `paper` has a dedicated endpoint in this phase; the others are indexed for entitlement/as-of/visibility but have no route in this file yet.
 */
export type ArchiveSectionKey = 'paper' | 'relations' | 'chart' | 'traits' | 'memories' | 'life';

export type V2ReasonCode = 'UNKNOWN_RESOURCE' | 'VISIBILITY_HELD' | 'WITHDRAWN' | 'RIGHTS_REVOKED' | 'PROJECTION_LAGGING' | 'CANONICAL_RESTRICTED' | 'MALFORMED_CURSOR';

export type PaperPositionStatus = 'open' | 'closed' | 'pending';

/**
 * Canonical paper-intent action set (system-design.md §9.2).
 */
export type PaperActionKind = 'BUY' | 'SELL' | 'HOLD' | 'NO_ACTION';

export type PaperDirection = 'no_action' | 'upside' | 'downside';

export type InvalidationCondition = 'not_yet_occurred' | 'occurred' | 'unknown_at_the_time';

/**
 * Whether `MarketSessionFinalityAccepted` has landed for a trading day.
 */
export type MarketSessionFinalityState = 'pending' | 'accepted';

export type DataRevisionKind = 'fact_correction' | 'accounting_correction' | 'position_adjustment';

export type Problem = {
    type: string;
    title: string;
    status: number;
    reasonCode: V2ReasonCode;
    traceId: string;
};

/**
 * One canonical aggregate/fact ref and the exact revision this projection was computed from. Part of the generic `sourceRevisionSet` required on every projection response; see `PaperVersionSet` for the fully-typed triple-aggregate version set used specifically by `/archive/paper`.
 */
export type SourceRevisionRef = {
    refId: string;
    refKind: string;
    revision: Version;
};

/**
 * The three-aggregate exact version set from `docs/v5/system-design.md` §9.1. `paperOrderRefs`/ `paperOrderVersions` and `paperPositionRefs`/`paperPositionVersions` are parallel arrays of equal length, pairwise ordered by stable aggregate ID byte order, with no duplicates. Any input or projection that only carries `paperAccountVersion` without the order/position arrays is not a valid version set.
 */
export type PaperVersionSet = {
    paperAccountRef: Uuid;
    paperAccountVersion: Version;
    paperOrderRefs: Array<Uuid>;
    paperOrderVersions: Array<Version>;
    paperPositionRefs: Array<Uuid>;
    paperPositionVersions: Array<Version>;
    paperVersionSetDigest: Digest;
};

/**
 * An immutable, server-resolved `UtteranceArtifactV1` reference plus its verbatim canonical bytes. Never paired with a second freeform "summary of what they said" string field (system-design.md §11.1, §11.4).
 */
export type CharacterUtterance = {
    utteranceArtifactId: string;
    canonicalTextSha256: Digest;
    canonicalTextUtf8: string;
};

/**
 * A later self-narration that is either a verbatim, artifact-backed quote (when a visible `UtteranceArtifactV1` exists) or an unquoted structured summary (the documented fallback shape from `docs/v5/experience-spec.md` §8.4 — never both, and never a system-authored quote).
 */
export type CharacterNarrationOrSummary = {
    kind: 'utterance';
    utteranceArtifactId: string;
    canonicalTextSha256: Digest;
    canonicalTextUtf8: string;
} | {
    kind: 'summary';
    summaryText: string;
};

/**
 * Stable-deep-link tombstone projection returned in place of a full character projection once `CharacterContinuityClassChanged` has moved a character to `WITHDRAWN` (system-design.md §3.1, §7.2.1). Existing public URLs never silently point at a different character or a different story.
 */
export type WithdrawnCharacterProjection = {
    projectionVersion: Version;
    sourceGlobalPosition: Version;
    serverNow: string;
    dataState: 'WITHDRAWN';
    visibilityEpoch: Version;
    truthClasses: Array<TruthClass>;
    sourceRevisionSet: Array<SourceRevisionRef>;
    characterId: Uuid;
    /**
     * Policy-safe, non-diagnostic label. Never includes `canonical_restricted` audit detail.
     */
    tombstoneReasonLabel: string;
};

export type AttentionTarget = {
    targetKind: 'person' | 'object' | 'event' | 'unknown';
    label: string;
};

export type UnresolvedCommitment = {
    commitmentId: Uuid;
    /**
     * Unquoted structured summary, never a system-authored quote.
     */
    rationaleSummary: string;
    sealedAt: string;
    stillOpen: boolean;
};

export type PaperPositionConsequenceHighlight = {
    kind: 'paper_position';
    positionArchiveRef: Uuid;
    /**
     * Signed percentage scaled by 100 (2 implied decimal places); e.g. -840 represents -8.40%.
     */
    unrealizedPnlPercentFixed2: number;
    /**
     * Always shown next to any paper figure (experience-spec §7.2); during a trading session this is the previous session's close.
     */
    asOf: string;
};

export type RelationshipConsequenceHighlight = {
    kind: 'relationship';
    dyadArchiveRef: Uuid;
    summary: string;
};

export type OccupationConsequenceHighlight = {
    kind: 'occupation';
    summary: string;
};

export type MemoryConsequenceHighlight = {
    kind: 'memory';
    summary: string;
};

/**
 * At most one consequence fragment, shown only when it is this scene's consequence; never a forced-empty performance figure (experience-spec §7.1–§7.2). Absent from `CharacterCloseUp` when there is nothing to show.
 */
export type RecentConsequenceHighlight = PaperPositionConsequenceHighlight | RelationshipConsequenceHighlight | OccupationConsequenceHighlight | MemoryConsequenceHighlight;

export type WorldMarketClock = {
    /**
     * Asia/Taipei market date (system-design.md §7.1).
     */
    marketDate: string;
    sessionPhase: MarketSessionPhase;
    /**
     * Previous finalized trading date backing any paper figures currently visible in the world; `null` when none exists yet.
     */
    asOfTradingDate: string | null;
    /**
     * Next versioned `DeadlineScheduled` boundary (system-design.md §7.1).
     */
    nextBoundaryAt: string;
};

export type WorldSceneState = {
    sceneId: Uuid;
    /**
     * At most two events with clear audiovisual priority at once (experience-spec §5.2).
     */
    activePriorityEventRefs: Array<Uuid>;
};

export type CharacterWorldPosition = {
    characterId: Uuid;
    /**
     * World-space grid coordinate.
     */
    worldX: number;
    /**
     * World-space grid coordinate.
     */
    worldY: number;
    poseState: CharacterPoseState;
    /**
     * What/who the character is currently attending to, if known.
     */
    focusHint: string | null;
    zOrder: number;
    sceneLayer: SceneLayer;
    detailTier: DetailTier;
    sourceEventRefs: Array<Uuid>;
};

/**
 * Lightweight public pointer into a scene, never a ranked or ticker-labeled recommendation (market-safety.md "今日五幕").
 */
export type WorldStoryHookRef = {
    hookId: Uuid;
    characterId: Uuid;
    sceneRef: Uuid;
    label: string;
};

export type WorldSnapshot = {
    projectionVersion: Version;
    sourceGlobalPosition: Version;
    serverNow: string;
    dataState: DataState;
    visibilityEpoch: Version;
    truthClasses: Array<TruthClass>;
    sourceRevisionSet: Array<SourceRevisionRef>;
    marketClock: WorldMarketClock;
    worldTickId: Version;
    scene: WorldSceneState;
    characterPositions: Array<CharacterWorldPosition>;
    /**
     * Mirrors the "今日五幕" 0–5 cap (experience-spec §5.4).
     */
    storyHooks: Array<WorldStoryHookRef>;
};

export type CharacterCloseUp = {
    projectionVersion: Version;
    sourceGlobalPosition: Version;
    serverNow: string;
    dataState: DataState;
    visibilityEpoch: Version;
    truthClasses: Array<TruthClass>;
    sourceRevisionSet: Array<SourceRevisionRef>;
    characterId: Uuid;
    displayName: string;
    ageYears: number;
    occupationLabel: string;
    sceneRef: Uuid;
    poseState: CharacterPoseState;
    /**
     * e.g. "正在偷看他說不在意的價格" (experience-spec §7.1).
     */
    currentVerbPhrase: string;
    currentAttention?: AttentionTarget;
    /**
     * The one unresolved-contradiction main sentence (experience-spec §7.1).
     */
    unresolvedTensionSummary: string;
    publicClaim?: CharacterUtterance;
    selfAcknowledgement?: CharacterUtterance;
    recentConsequenceHighlight?: RecentConsequenceHighlight;
    unresolvedCommitments: Array<UnresolvedCommitment>;
};

export type CharacterCloseUpResponse = CharacterCloseUp | WithdrawnCharacterProjection;

export type PaperConsequenceFragment = {
    positionArchiveRef: Uuid;
    heldDays: number;
    /**
     * Signed currency minor units.
     */
    unrealizedPnlMinorUnits: number;
    /**
     * Signed percentage scaled by 100 (2 implied decimal places).
     */
    unrealizedPnlPercentFixed2: number;
    asOf: string;
};

export type LifeJournalConsequence = unknown & {
    paperConsequence?: PaperConsequenceFragment;
    nonPaperConsequenceSummary?: string;
};

/**
 * Only refs into `/archive*` sections — never the full ledger, relationship graph, or memory index inline (system-design.md §11.3).
 */
export type LifeJournalArchiveRefs = {
    paperPositionRefs: Array<Uuid>;
    relationshipDyadRefs: Array<Uuid>;
    memoryRefs: Array<Uuid>;
};

/**
 * One canonical day-chapter, ordered per experience-spec §8.1.
 */
export type LifeJournalEntry = {
    entryId: Uuid;
    chapterDate: string;
    /**
     * 今天他怎麼了
     */
    sceneSummary: string;
    /**
     * 他當時怎麼說 — original self-statement, never rewritten after the fact; absent if nothing was said.
     */
    contemporaneousClaim?: CharacterUtterance;
    /**
     * 他其實知道什麼 — only material the character had actually encountered by then.
     */
    knownAtTheTimeSummary: string;
    /**
     * 他漏掉了什麼 — only revealed after close or after the relevant data went public.
     */
    missedFactsSummary?: string;
    /**
     * 他做了什麼 — structured summary of the paper action, wait, ask-for-help, concealment, or withdrawal.
     */
    actionSummary: string;
    consequence: LifeJournalConsequence;
    currentSelfNarration?: CharacterNarrationOrSummary;
    /**
     * 老毛病又回來了 — present only once the same pattern has recurred at least twice.
     */
    recurringPatternRef?: Uuid;
    /**
     * 還沒完 — the next unresolved question; never previews the outcome.
     */
    openQuestionSummary: string;
    archiveRefs: LifeJournalArchiveRefs;
};

export type LifeJournalPage = {
    projectionVersion: Version;
    sourceGlobalPosition: Version;
    serverNow: string;
    dataState: DataState;
    visibilityEpoch: Version;
    truthClasses: Array<TruthClass>;
    sourceRevisionSet: Array<SourceRevisionRef>;
    characterId: Uuid;
    appliedAudienceScope: AudienceScope;
    entries: Array<LifeJournalEntry>;
    nextCursor: string | null;
};

export type CharacterLifeJournalResponse = LifeJournalPage | WithdrawnCharacterProjection;

export type ArchiveSectionIndexEntry = {
    sectionKey: ArchiveSectionKey;
    /**
     * The audience scope actually applied for the requesting viewer on this section (system-design.md §11.3 audience table).
     */
    viewerAudienceScope: AudienceScope;
    /**
     * One-line index summary, e.g. "目前 2 個部位，其中 1 個理由已失效。"
     */
    summary: string;
    asOf: string;
    visibilityEpoch: Version;
    /**
     * Same-origin path for this section's dedicated endpoint, or `null` if it has none in this phase (see `ArchiveSectionKey`).
     */
    sectionPath: string | null;
};

export type CharacterArchiveIndex = {
    projectionVersion: Version;
    sourceGlobalPosition: Version;
    serverNow: string;
    dataState: DataState;
    visibilityEpoch: Version;
    truthClasses: Array<TruthClass>;
    sourceRevisionSet: Array<SourceRevisionRef>;
    characterId: Uuid;
    archiveSchemaRevision: string;
    longTermTensionSummary: string;
    /**
     * 最近留下的三件事 (experience-spec §9.1).
     */
    recentHighlights: Array<string>;
    /**
     * One entry per `ArchiveSectionKey` value.
     */
    sections: [
        ArchiveSectionIndexEntry,
        ArchiveSectionIndexEntry,
        ArchiveSectionIndexEntry,
        ArchiveSectionIndexEntry,
        ArchiveSectionIndexEntry,
        ArchiveSectionIndexEntry
    ];
};

export type CharacterArchiveIndexResponse = CharacterArchiveIndex | WithdrawnCharacterProjection;

/**
 * Public projection of `PaperAccount` authoritative fields only — never order lifecycle, fill state, lots, or position P&L (system-design.md §9.1).
 */
export type PaperAccountPublicSummary = {
    currency: string;
    cashMinorUnits: number;
    reservedCashMinorUnits: number;
    /**
     * Baseline virtual principal (e.g. NT$1,000,000; system-design.md §9.1).
     */
    initialCapitalMinorUnits: number;
    correctionRefs: Array<Uuid>;
    asOf: string;
};

export type PaperLotPublic = {
    lotId: Uuid;
    /**
     * Quantity scaled by 1,000,000 (integer fixed-point; never float).
     */
    quantityFixed6: number;
    /**
     * Per-unit sealed reference price in currency minor units, further scaled by 1,000,000 for sub-minor-unit precision.
     */
    sealedPriceMinorUnitsFixed6: number;
    /**
     * Total lot cost basis in currency minor units.
     */
    costBasisMinorUnits: number;
    sealedPriceRevisionRef: Digest;
};

export type PaperPositionPublic = {
    positionId: Uuid;
    /**
     * Company name/ticker label only — never a recommendation badge.
     */
    instrumentLabel: string;
    status: PaperPositionStatus;
    openedAt: string;
    lastChangedAt: string;
    closedAt: string | null;
    lots: Array<PaperLotPublic>;
    realizedPnlMinorUnits: number | null;
    unrealizedPnlMinorUnits: number | null;
    unrealizedPnlPercentFixed2: number | null;
    markAsOf: string;
    invalidationCondition: InvalidationCondition;
    /**
     * Unquoted structured summary sealed at the time, never a quote.
     */
    rationaleSummary: string;
    /**
     * 同時原話 — present only if a visible UtteranceArtifactV1 exists.
     */
    concurrentClaim?: CharacterUtterance;
    currentNarration?: CharacterNarrationOrSummary;
    influencedByCharacterRefs: Array<Uuid>;
    consequenceSummary: string;
};

/**
 * Same-day ticker-specific action, direction, quantity, confidence, and fill. This object is structurally absent from `PaperActionFillRecord` until `MarketSessionFinalityAccepted` is recorded for that trading day — never present with nulled fields (market-safety.md "當期交易時段不得公開" / "盤後才可公開").
 */
export type PaperDailyActionDisclosure = {
    instrumentLabel: string;
    action: PaperActionKind;
    direction: PaperDirection;
    /**
     * Quantity scaled by 1,000,000.
     */
    quantityFixed6: number;
    /**
     * Signed percentage scaled by 100 (2 implied decimal places).
     */
    confidencePercentFixed2: number;
    /**
     * `null` when the order expired unfilled (`PaperOrderExpired`).
     */
    fill: {
        sealedPriceMinorUnitsFixed6: number;
        sealedPriceRevisionRef: Digest;
        filledAt: string;
    } | null;
    /**
     * Unquoted structured summary sealed before action, never a quote.
     */
    rationaleSummary: string;
    concurrentClaim?: CharacterUtterance;
};

/**
 * `dailyActionDisclosure` is an optional key that is only ever serialized once `marketSessionFinalityState` is `accepted` for this record's `tradingDate`; pre-finality responses omit the key entirely rather than sending it nulled out.
 */
export type PaperActionFillRecord = {
    recordId: Uuid;
    positionRef: Uuid;
    /**
     * Asia/Taipei trading session date.
     */
    tradingDate: string;
    marketSessionFinalityState: MarketSessionFinalityState;
    recordDataState: DataState;
    dailyActionDisclosure?: PaperDailyActionDisclosure;
};

export type DataRevisionNote = {
    revisionId: string;
    appliedAt: string;
    kind: DataRevisionKind;
    affectedRefs: Array<Uuid>;
    summary: string;
};

export type PaperArchiveProjection = {
    projectionVersion: Version;
    sourceGlobalPosition: Version;
    serverNow: string;
    dataState: DataState;
    visibilityEpoch: Version;
    truthClasses: Array<TruthClass>;
    sourceRevisionSet: Array<SourceRevisionRef>;
    characterId: Uuid;
    appliedAudienceScope: AudienceScope;
    /**
     * Explicit as-of for the whole projection; intraday this is always the previous trading session's close (experience-spec §7.2, §9.4).
     */
    asOf: string;
    paperVersionSet: PaperVersionSet;
    account: PaperAccountPublicSummary;
    positions: Array<PaperPositionPublic>;
    historicalActionFills: Array<PaperActionFillRecord>;
    dataRevisions: Array<DataRevisionNote>;
};

export type CharacterPaperArchiveResponse = PaperArchiveProjection | WithdrawnCharacterProjection;

/**
 * The JSON shape carried in each SSE frame's `data:` field for `GET /events/v2/world`. This only signals "resource changed" — never authoritative content; clients must re-`GET` `resourceRef`.
 */
export type WorldStreamEventEnvelope = {
    eventKind: 'world_tick' | 'scene_change' | 'character_event' | 'projection_checkpoint';
    /**
     * Same-origin public path the client should re-`GET`, e.g. `/api/v2/world` or `/api/v2/characters/{id}/close-up`. Never a source of truth by itself.
     */
    resourceRef: string;
    /**
     * Reconnect cursor; resend as `Last-Event-ID` (or the SSE `id:` field carries the same value) to resume from this checkpoint.
     */
    checkpointCursor: string;
    visibilityEpoch: Version;
    serverNow: string;
};

export type CharacterId = Uuid;

export type Cursor = string;

export type Limit = number;

export type LastEventId = string;

export type GetWorldSnapshotData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v2/world';
};

export type GetWorldSnapshotErrors = {
    /**
     * Unknown or inaccessible resource.
     */
    404: Problem;
};

export type GetWorldSnapshotError = GetWorldSnapshotErrors[keyof GetWorldSnapshotErrors];

export type GetWorldSnapshotResponses = {
    /**
     * Current public world snapshot.
     */
    200: WorldSnapshot;
};

export type GetWorldSnapshotResponse = GetWorldSnapshotResponses[keyof GetWorldSnapshotResponses];

export type GetCharacterCloseUpData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/v2/characters/{id}/close-up';
};

export type GetCharacterCloseUpErrors = {
    /**
     * Unknown or inaccessible resource.
     */
    404: Problem;
};

export type GetCharacterCloseUpError = GetCharacterCloseUpErrors[keyof GetCharacterCloseUpErrors];

export type GetCharacterCloseUpResponses = {
    /**
     * Character close-up, or a tombstone projection if the character has been withdrawn.
     */
    200: CharacterCloseUpResponse;
};

export type GetCharacterCloseUpResponse = GetCharacterCloseUpResponses[keyof GetCharacterCloseUpResponses];

export type GetCharacterLifeJournalData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/api/v2/characters/{id}/life-journal';
};

export type GetCharacterLifeJournalErrors = {
    /**
     * Malformed or expired cursor.
     */
    400: Problem;
    /**
     * Unknown or inaccessible resource.
     */
    404: Problem;
};

export type GetCharacterLifeJournalError = GetCharacterLifeJournalErrors[keyof GetCharacterLifeJournalErrors];

export type GetCharacterLifeJournalResponses = {
    /**
     * One page of life-journal entries, or a tombstone projection if the character has been withdrawn.
     */
    200: CharacterLifeJournalResponse;
};

export type GetCharacterLifeJournalResponse = GetCharacterLifeJournalResponses[keyof GetCharacterLifeJournalResponses];

export type GetCharacterArchiveIndexData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/v2/characters/{id}/archive';
};

export type GetCharacterArchiveIndexErrors = {
    /**
     * Unknown or inaccessible resource.
     */
    404: Problem;
};

export type GetCharacterArchiveIndexError = GetCharacterArchiveIndexErrors[keyof GetCharacterArchiveIndexErrors];

export type GetCharacterArchiveIndexResponses = {
    /**
     * Deep-archive index, or a tombstone projection if the character has been withdrawn.
     */
    200: CharacterArchiveIndexResponse;
};

export type GetCharacterArchiveIndexResponse = GetCharacterArchiveIndexResponses[keyof GetCharacterArchiveIndexResponses];

export type GetCharacterPaperArchiveData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/v2/characters/{id}/archive/paper';
};

export type GetCharacterPaperArchiveErrors = {
    /**
     * Unknown or inaccessible resource.
     */
    404: Problem;
};

export type GetCharacterPaperArchiveError = GetCharacterPaperArchiveErrors[keyof GetCharacterPaperArchiveErrors];

export type GetCharacterPaperArchiveResponses = {
    /**
     * Public paper-trading archive projection, or a tombstone projection if the character has been withdrawn.
     */
    200: CharacterPaperArchiveResponse;
};

export type GetCharacterPaperArchiveResponse = GetCharacterPaperArchiveResponses[keyof GetCharacterPaperArchiveResponses];

export type StreamWorldEventsData = {
    body?: never;
    headers?: {
        'Last-Event-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/events/v2/world';
};

export type StreamWorldEventsErrors = {
    /**
     * Malformed or expired `Last-Event-ID` reconnect cursor.
     */
    400: Problem;
};

export type StreamWorldEventsError = StreamWorldEventsErrors[keyof StreamWorldEventsErrors];

export type StreamWorldEventsResponses = {
    /**
     * Open SSE stream. Each frame's `data:` payload is one `WorldStreamEventEnvelope`.
     */
    200: WorldStreamEventEnvelope;
};

export type StreamWorldEventsResponse = StreamWorldEventsResponses[keyof StreamWorldEventsResponses];
